import type { CSSProperties } from 'react';

export const s: Record<string, CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    fontSize: 13,
    color: '#e5e7eb',
  },
  topBar: {
    display: 'flex',
    gap: 6,
    padding: '8px 8px 4px',
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    padding: '5px 9px',
    borderRadius: 6,
    border: '1px solid #374151',
    background: '#0f172a',
    color: '#e5e7eb',
    fontSize: 13,
    outline: 'none',
  },
  addBtn: {
    padding: '5px 13px',
    borderRadius: 6,
    border: 'none',
    background: '#3b82f6',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 13,
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  tabBar: {
    display: 'flex',
    gap: 1,
    padding: '2px 8px',
    overflowX: 'auto',
    flexShrink: 0,
    scrollbarWidth: 'none',
  },
  tab: {
    padding: '3px 9px',
    border: 'none',
    borderRadius: 5,
    background: 'transparent',
    color: '#6b7280',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
    whiteSpace: 'nowrap',
  },
  tabOn: {
    background: '#1e293b',
    color: '#f3f4f6',
  },
  chips: {
    display: 'flex',
    gap: 4,
    padding: '3px 8px 6px',
    overflowX: 'auto',
    flexShrink: 0,
    scrollbarWidth: 'none',
  },
  chip: {
    padding: '2px 8px',
    borderRadius: 20,
    border: '1px solid #374151',
    background: 'transparent',
    color: '#6b7280',
    cursor: 'pointer',
    fontSize: 11,
    whiteSpace: 'nowrap',
  },
  chipOn: {
    background: '#1e293b',
    color: '#e5e7eb',
    borderColor: '#475569',
  },
  list: {
    flex: 1,
    overflowY: 'auto',
    padding: '2px 8px 8px',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 8,
    alignItems: 'start',
  },
  iconBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 13,
    padding: '2px 3px',
    borderRadius: 4,
    opacity: 0.55,
    lineHeight: 1,
    color: 'inherit',
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.65)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  modal: {
    background: '#1e293b',
    borderRadius: 10,
    padding: '20px 22px',
    width: 370,
    maxWidth: '92vw',
    maxHeight: '87vh',
    overflowY: 'auto',
    boxShadow: '0 25px 60px rgba(0,0,0,0.6)',
  },
  fieldLabel: {
    display: 'block',
    fontSize: 10,
    fontWeight: 700,
    color: '#64748b',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  field: {
    width: '100%',
    padding: '7px 10px',
    borderRadius: 6,
    border: '1px solid #334155',
    background: '#0f172a',
    color: '#e5e7eb',
    fontSize: 13,
    outline: 'none',
    marginBottom: 12,
    boxSizing: 'border-box',
    fontFamily: 'inherit',
  },
  cancelBtn: {
    flex: 1,
    padding: '8px',
    borderRadius: 6,
    border: '1px solid #334155',
    background: 'transparent',
    color: '#94a3b8',
    cursor: 'pointer',
    fontSize: 13,
  },
  saveBtn: {
    flex: 1,
    padding: '8px',
    borderRadius: 6,
    border: 'none',
    background: '#3b82f6',
    color: '#fff',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
  },
};
